let clasificacion = {
  filters: {},
  competition: {
    id: 2014,
    area: {
      id: 2224,
      name: "Spain",
    },
    name: "Primera Division",
    code: "PD",
    plan: "TIER_ONE",
    lastUpdated: "2022-03-20T09:20:08Z",
  },
  season: {
    id: 1504,
    startDate: "2022-08-14",
    endDate: "2023-06-04",
    currentMatchday: 8,
    winner: null,
  },
  standings: [
    {
      stage: "REGULAR_SEASON",
      type: "TOTAL",
      group: null,
      table: [
        {
          position: 1,
          team: {
            id: 81,
            name: "FC Barcelona",
            crestUrl: "https://crests.football-data.org/81.svg",
          },
          playedGames: 8,
          form: null,
          won: 7,
          draw: 1,
          lost: 0,
          points: 22,
          goalsFor: 20,
          goalsAgainst: 1,
          goalDifference: 19,
        },
        {
          position: 2,
          team: {
            id: 86,
            name: "Real Madrid CF",
            crestUrl: "https://crests.football-data.org/86.png",
          },
          playedGames: 8,
          form: null,
          won: 7,
          draw: 1,
          lost: 0,
          points: 22,
          goalsFor: 19,
          goalsAgainst: 7,
          goalDifference: 12,
        },
        {
          position: 3,
          team: {
            id: 77,
            name: "Athletic Club",
            crestUrl: "https://crests.football-data.org/77.png",
          },
          playedGames: 8,
          form: null,
          won: 5,
          draw: 2,
          lost: 1,
          points: 17,
          goalsFor: 17,
          goalsAgainst: 5,
          goalDifference: 12,
        },
        {
          position: 4,
          team: {
            id: 78,
            name: "Club Atlético de Madrid",
            crestUrl: "https://crests.football-data.org/78.svg",
          },
          playedGames: 8,
          form: null,
          won: 5,
          draw: 1,
          lost: 2,
          points: 16,
          goalsFor: 14,
          goalsAgainst: 7,
          goalDifference: 7,
        },
        {
          position: 5,
          team: {
            id: 90,
            name: "Real Betis Balompié",
            crestUrl: "https://crests.football-data.org/90.png",
          },
          playedGames: 8,
          form: null,
          won: 5,
          draw: 1,
          lost: 2,
          points: 16,
          goalsFor: 10,
          goalsAgainst: 5,
          goalDifference: 5,
        },
        {
          position: 6,
          team: {
            id: 92,
            name: "Real Sociedad de Fútbol",
            crestUrl: "https://crests.football-data.org/92.svg",
          },
          playedGames: 8,
          form: null,
          won: 5,
          draw: 1,
          lost: 2,
          points: 16,
          goalsFor: 13,
          goalsAgainst: 11,
          goalDifference: 2,
        },
        {
          position: 7,
          team: {
            id: 95,
            name: "Valencia CF",
            crestUrl: "https://crests.football-data.org/95.svg",
          },
          playedGames: 8,
          form: null,
          won: 4,
          draw: 1,
          lost: 3,
          points: 13,
          goalsFor: 14,
          goalsAgainst: 8,
          goalDifference: 6,
        },
        {
          position: 8,
          team: {
            id: 79,
            name: "CA Osasuna",
            crestUrl: "https://crests.football-data.org/79.svg",
          },
          playedGames: 8,
          form: null,
          won: 4,
          draw: 1,
          lost: 3,
          points: 13,
          goalsFor: 9,
          goalsAgainst: 8,
          goalDifference: 1,
        },
        {
          position: 9,
          team: {
            id: 94,
            name: "Villarreal CF",
            crestUrl: "https://crests.football-data.org/94.png",
          },
          playedGames: 8,
          form: null,
          won: 3,
          draw: 3,
          lost: 2,
          points: 12,
          goalsFor: 10,
          goalsAgainst: 3,
          goalDifference: 7,
        },
        {
          position: 10,
          team: {
            id: 87,
            name: "Rayo Vallecano de Madrid",
            crestUrl: "https://crests.football-data.org/87.svg",
          },
          playedGames: 8,
          form: null,
          won: 3,
          draw: 1,
          lost: 4,
          points: 10,
          goalsFor: 10,
          goalsAgainst: 12,
          goalDifference: -2,
        },
        {
          position: 11,
          team: {
            id: 558,
            name: "RC Celta de Vigo",
            crestUrl: "https://crests.football-data.org/558.svg",
          },
          playedGames: 8,
          form: null,
          won: 3,
          draw: 1,
          lost: 4,
          points: 10,
          goalsFor: 9,
          goalsAgainst: 14,
          goalDifference: -5,
        },
        {
          position: 12,
          team: {
            id: 89,
            name: "RCD Mallorca",
            crestUrl: "https://crests.football-data.org/89.png",
          },
          playedGames: 8,
          form: null,
          won: 2,
          draw: 3,
          lost: 3,
          points: 9,
          goalsFor: 7,
          goalsAgainst: 9,
          goalDifference: -2,
        },
        {
          position: 13,
          team: {
            id: 250,
            name: "Real Valladolid CF",
            crestUrl: "https://crests.football-data.org/250.png",
          },
          playedGames: 8,
          form: null,
          won: 2,
          draw: 2,
          lost: 4,
          points: 8,
          goalsFor: 6,
          goalsAgainst: 13,
          goalDifference: -7,
        },
        {
          position: 14,
          team: {
            id: 298,
            name: "Girona FC",
            crestUrl: "https://crests.football-data.org/298.png",
          },
          playedGames: 8,
          form: null,
          won: 2,
          draw: 1,
          lost: 5,
          points: 7,
          goalsFor: 11,
          goalsAgainst: 14,
          goalDifference: -3,
        },
        {
          position: 15,
          team: {
            id: 267,
            name: "UD Almería",
            crestUrl: "https://crests.football-data.org/267.png",
          },
          playedGames: 8,
          form: null,
          won: 2,
          draw: 1,
          lost: 5,
          points: 7,
          goalsFor: 7,
          goalsAgainst: 12,
          goalDifference: -5,
        },
        {
          position: 16,
          team: {
            id: 82,
            name: "Getafe CF",
            crestUrl: "https://crests.football-data.org/82.png",
          },
          playedGames: 8,
          form: null,
          won: 2,
          draw: 1,
          lost: 5,
          points: 7,
          goalsFor: 8,
          goalsAgainst: 16,
          goalDifference: -8,
        },
        {
          position: 17,
          team: {
            id: 80,
            name: "RCD Espanyol de Barcelona",
            crestUrl: "https://crests.football-data.org/80.svg",
          },
          playedGames: 8,
          form: null,
          won: 1,
          draw: 3,
          lost: 4,
          points: 6,
          goalsFor: 11,
          goalsAgainst: 16,
          goalDifference: -5,
        },
        {
          position: 18,
          team: {
            id: 559,
            name: "Sevilla FC",
            crestUrl: "https://crests.football-data.org/559.svg",
          },
          playedGames: 8,
          form: null,
          won: 1,
          draw: 3,
          lost: 4,
          points: 6,
          goalsFor: 8,
          goalsAgainst: 14,
          goalDifference: -6,
        },
        {
          position: 19,
          team: {
            id: 264,
            name: "Cádiz CF",
            crestUrl: "https://crests.football-data.org/264.png",
          },
          playedGames: 8,
          form: null,
          won: 1,
          draw: 2,
          lost: 5,
          points: 5,
          goalsFor: 3,
          goalsAgainst: 16,
          goalDifference: -13,
        },
        {
          position: 20,
          team: {
            id: 285,
            name: "Elche CF",
            crestUrl: "https://crests.football-data.org/285.png",
          },
          playedGames: 8,
          form: null,
          won: 0,
          draw: 2,
          lost: 6,
          points: 2,
          goalsFor: 4,
          goalsAgainst: 19,
          goalDifference: -15,
        },
      ],
    },
  ],
};
