let proximosp = {
  filters: {
    dateFrom: "2022-10-17",
    dateTo: "2022-10-18",
    permission: "TIER_ONE",
  },
  resultSet: {
    count: 4,
    competitions: "SA,PD,BSA",
    first: "2022-10-17",
    last: "2022-10-17",
    played: 0,
  },
  matches: [
    {
      area: {
        id: 2114,
        name: "Italy",
        code: "ITA",
        flag: "https://crests.football-data.org/784.svg",
      },
      competition: {
        id: 2019,
        name: "Serie A",
        code: "SA",
        type: "LEAGUE",
        emblem: "https://crests.football-data.org/SA.png",
      },
      season: {
        id: 1505,
        startDate: "2022-08-14",
        endDate: "2023-06-04",
        currentMatchday: 10,
        winner: null,
      },
      id: 418816,
      utcDate: "2022-10-17T16:30:00Z",
      status: "TIMED",
      matchday: 10,
      stage: "REGULAR_SEASON",
      group: null,
      lastUpdated: "2022-10-17T14:30:17Z",
      homeTeam: {
        id: 584,
        name: "UC Sampdoria",
        shortName: "Sampdoria",
        tla: "SAM",
        crest: "https://crests.football-data.org/584.svg",
      },
      awayTeam: {
        id: 100,
        name: "AS Roma",
        shortName: "Roma",
        tla: "ROM",
        crest: "https://crests.football-data.org/100.svg",
      },
      score: {
        winner: null,
        duration: "REGULAR",
        fullTime: {
          home: null,
          away: null,
        },
        halfTime: {
          home: null,
          away: null,
        },
      },
      odds: {
        msg: "Activate Odds-Package in User-Panel to retrieve odds.",
      },
      referees: [
        {
          id: 11060,
          name: "Marco Di Bello",
          type: "REFEREE",
          nationality: "Italy",
        },
      ],
    },
    {
      area: {
        id: 2114,
        name: "Italy",
        code: "ITA",
        flag: "https://crests.football-data.org/784.svg",
      },
      competition: {
        id: 2019,
        name: "Serie A",
        code: "SA",
        type: "LEAGUE",
        emblem: "https://crests.football-data.org/SA.png",
      },
      season: {
        id: 1505,
        startDate: "2022-08-14",
        endDate: "2023-06-04",
        currentMatchday: 10,
        winner: null,
      },
      id: 418818,
      utcDate: "2022-10-17T18:45:00Z",
      status: "TIMED",
      matchday: 10,
      stage: "REGULAR_SEASON",
      group: null,
      lastUpdated: "2022-10-17T16:45:19Z",
      homeTeam: {
        id: 5890,
        name: "US Lecce",
        shortName: "Lecce",
        tla: "USL",
        crest: "https://crests.football-data.org/5890.png",
      },
      awayTeam: {
        id: 99,
        name: "ACF Fiorentina",
        shortName: "Fiorentina",
        tla: "FIO",
        crest: "https://crests.football-data.org/99.svg",
      },
      score: {
        winner: null,
        duration: "REGULAR",
        fullTime: {
          home: null,
          away: null,
        },
        halfTime: {
          home: null,
          away: null,
        },
      },
      odds: {
        msg: "Activate Odds-Package in User-Panel to retrieve odds.",
      },
      referees: [
        {
          id: 57836,
          name: "Luca Massimi",
          type: "REFEREE",
          nationality: "Italy",
        },
      ],
    },
    {
      area: {
        id: 2224,
        name: "Spain",
        code: "ESP",
        flag: "https://crests.football-data.org/760.svg",
      },
      competition: {
        id: 2014,
        name: "Primera Division",
        code: "PD",
        type: "LEAGUE",
        emblem: "https://crests.football-data.org/PD.png",
      },
      season: {
        id: 1504,
        startDate: "2022-08-14",
        endDate: "2023-06-04",
        currentMatchday: 9,
        winner: null,
      },
      id: 419205,
      utcDate: "2022-10-17T19:00:00Z",
      status: "TIMED",
      matchday: 9,
      stage: "REGULAR_SEASON",
      group: null,
      lastUpdated: "2022-10-17T17:00:19Z",
      homeTeam: {
        id: 94,
        name: "Villarreal CF",
        shortName: "Villarreal",
        tla: "VIL",
        crest: "https://crests.football-data.org/94.png",
      },
      awayTeam: {
        id: 79,
        name: "CA Osasuna",
        shortName: "Osasuna",
        tla: "OSA",
        crest: "https://crests.football-data.org/79.svg",
      },
      score: {
        winner: null,
        duration: "REGULAR",
        fullTime: {
          home: null,
          away: null,
        },
        halfTime: {
          home: null,
          away: null,
        },
      },
      odds: {
        msg: "Activate Odds-Package in User-Panel to retrieve odds.",
      },
      referees: [
        {
          id: 56978,
          name: "Pablo González",
          type: "REFEREE",
          nationality: "Spain",
        },
      ],
    },
    {
      area: {
        id: 2032,
        name: "Brazil",
        code: "BRA",
        flag: "https://crests.football-data.org/764.svg",
      },
      competition: {
        id: 2013,
        name: "Campeonato Brasileiro Série A",
        code: "BSA",
        type: "LEAGUE",
        emblem: "https://crests.football-data.org/764.svg",
      },
      season: {
        id: 1377,
        startDate: "2022-04-10",
        endDate: "2022-11-13",
        currentMatchday: 32,
        winner: null,
      },
      id: 390083,
      utcDate: "2022-10-17T23:00:00Z",
      status: "TIMED",
      matchday: 32,
      stage: "REGULAR_SEASON",
      group: null,
      lastUpdated: "2022-10-17T01:32:00Z",
      homeTeam: {
        id: 4286,
        name: "RB Bragantino",
        shortName: "Bragantino",
        tla: "RBB",
        crest: "https://crests.football-data.org/4286.svg",
      },
      awayTeam: {
        id: 6685,
        name: "Santos FC",
        shortName: "Santos",
        tla: "SAN",
        crest: "https://crests.football-data.org/6685.svg",
      },
      score: {
        winner: null,
        duration: "REGULAR",
        fullTime: {
          home: null,
          away: null,
        },
        halfTime: {
          home: null,
          away: null,
        },
      },
      odds: {
        msg: "Activate Odds-Package in User-Panel to retrieve odds.",
      },
      referees: [],
    },
  ],
};
